name: VirtualStorages
version: 1.2.2
author: DaveDuart
main: net.duart.virtualstorage.VirtualStorages
api-version: 1.20

commands:
  backpack:
    description: Opens the virtual backpack inventory.
    usage: /backpack
    aliases: [bp]
  vsreload:
    description: Reloads VirtualStorages permissions and configurations.
    usage: /vsreload